/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baranggudang;

import java.sql.Connection;
import java.sql.PreparedStatement;
import KoneksiDb.Koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deano
 */
public class DaftarGudang extends javax.swing.JFrame {
    static Connection conn;
    static String sql;
    PreparedStatement ps;
    ResultSet rs;
    static Statement st;
    
    //variabel untuk insert
    String nama,merek,jenis,panjang,lebar,tanggalmasuk,tujuan,tanggalkeluar;
    
    //variabel untuk update
    String namaup,merekup,jenisup,panjangup,lebarup,tanggalmasukup,tujuanup,tanggalkeluarup,noup;

    /**
     * Creates new form DaftarGudang
     */
    public DaftarGudang() {
        conn = new Koneksi().SetConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupJenis = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MerekBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PecahBelah = new javax.swing.JRadioButton();
        Normal = new javax.swing.JRadioButton();
        PanjangBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TanggalMasuk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TujuanBarang = new javax.swing.JTextField();
        TanggalKeluar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        ShowBarang = new javax.swing.JButton();
        Bersih = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        NoBarang = new javax.swing.JTextField();
        TombolDel = new javax.swing.JButton();
        TombolUp = new javax.swing.JButton();
        LihatData = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LebarBarang = new javax.swing.JTextField();
        ResetBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Daftar barang masuk");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama barang");

        NamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Merek barang");

        MerekBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MerekBarangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jenis barang");

        GrupJenis.add(PecahBelah);
        PecahBelah.setText("Pecah belah");
        PecahBelah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PecahBelahActionPerformed(evt);
            }
        });

        GrupJenis.add(Normal);
        Normal.setText("normal");
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });

        PanjangBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanjangBarangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Panjang Barang (cm)");

        TanggalMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalMasukActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal masuk");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tujuan barang");

        TujuanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuanBarangActionPerformed(evt);
            }
        });

        TanggalKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalKeluarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal keluar");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No barang", "Nama", "merek", "jenis", "Panjang", "Lebar", "tanggal masuk", "tujuan ", "tanggal keluar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableBarang);

        ShowBarang.setText("Show");
        ShowBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBarangActionPerformed(evt);
            }
        });

        Bersih.setText("Clear");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nomor barang");

        TombolDel.setText("Delete");
        TombolDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDelActionPerformed(evt);
            }
        });

        TombolUp.setText("Update");
        TombolUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolUpActionPerformed(evt);
            }
        });

        LihatData.setText("Lihat data");
        LihatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatDataActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Update dan Delete");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Lebar Barang (cm)");

        LebarBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebarBarangActionPerformed(evt);
            }
        });

        ResetBarang.setText("reset no barang");
        ResetBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PecahBelah)
                                .addGap(18, 18, 18)
                                .addComponent(Normal))
                            .addComponent(jLabel2)
                            .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(MerekBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(PanjangBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(TanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TujuanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Bersih)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))
                                .addComponent(TanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResetBarang)
                                .addGap(26, 26, 26)
                                .addComponent(ShowBarang))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LihatData)
                                                .addGap(18, 18, 18)
                                                .addComponent(TombolUp)
                                                .addGap(18, 18, 18)
                                                .addComponent(TombolDel))
                                            .addComponent(NoBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 528, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(LebarBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MerekBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PecahBelah)
                            .addComponent(Normal)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ShowBarang)
                    .addComponent(ResetBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanjangBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LebarBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LihatData)
                            .addComponent(TombolUp)
                            .addComponent(TombolDel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(TujuanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(Bersih))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaBarangActionPerformed

    private void MerekBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MerekBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MerekBarangActionPerformed

    private void PecahBelahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PecahBelahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PecahBelahActionPerformed

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NormalActionPerformed

    private void PanjangBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanjangBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanjangBarangActionPerformed

    private void TanggalMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalMasukActionPerformed

    private void TujuanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuanBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TujuanBarangActionPerformed

    private void TanggalKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalKeluarActionPerformed

    
    //tombol dan fungsi untuk memasukan data
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nama = NamaBarang.getText();
        merek = MerekBarang.getText();
        jenis = "";
        if (PecahBelah.isSelected()){
            jenis = PecahBelah.getText();
        }
        else if (Normal.isSelected()){
            jenis = Normal.getText();
        }
        else{
           jenis = "belum memilih";
        }
        panjang = PanjangBarang.getText();
        lebar = LebarBarang.getText();
        tanggalmasuk = TanggalMasuk.getText();
        tujuan = TujuanBarang.getText();
        tanggalkeluar = TanggalKeluar.getText();
        
        
        try{
            sql = "INSERT INTO daftar_barang VALUES (?,?,?,?,?,?,?,?,?)";
            ps = conn.prepareStatement(sql);
            
            ps.setInt(1,0);
            ps.setString(2, nama);
            ps.setString(3, merek);
            ps.setString(4, jenis);
            ps.setString(5, panjang);
            ps.setString(6, lebar);
            ps.setString(7, tanggalmasuk);
            ps.setString(8, tujuan);
            ps.setString(9, tanggalkeluar);
            ps.setInt(1,0);
            
            
                //validasi untuk memasukan data
                if (NamaBarang.getText().equals("")) {
                     JOptionPane.showMessageDialog(null, "nama tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                } else if (MerekBarang.getText().equals("")) {
                     JOptionPane.showMessageDialog(null, "merek tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                } else if (PecahBelah.isSelected() == false && Normal.isSelected() == false ) {
                     JOptionPane.showMessageDialog(null, "jenis tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }else if (PanjangBarang.getText().equals("")) {
                     JOptionPane.showMessageDialog(null, "panjang tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }else if (LebarBarang.getText().equals("")) {
                     JOptionPane.showMessageDialog(null, "lebar tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }else if (TanggalMasuk.getText().equals("")) {
                     JOptionPane.showMessageDialog(null, "tanggal masuk tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }else if (TujuanBarang.getText().equals("")) {
                     JOptionPane.showMessageDialog(null, "tujuan tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }else if (TanggalKeluar.getText().equals("")) {
                     JOptionPane.showMessageDialog(null, "tanggal keluar tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }else{
                    int rt = ps.executeUpdate();
                 JOptionPane.showMessageDialog(null,"Data berhasil disimpan", "information", JOptionPane.INFORMATION_MESSAGE );
                }

            
        }catch (Exception e) {
            System.out.println("error : "+ e.getMessage());
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    
    //tombol dan fungsi untuk menampilkan data
    private void ShowBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBarangActionPerformed
        // TODO add your handling code here:
        try{
             String query = "SELECT id_barang,nama_barang,merek_barang,jenis_barang,panjang_barang,lebar_barang,tanggal_masuk,tujuan_barang,tanggal_keluar FROM daftar_barang";
             st = conn.createStatement();
             rs = st.executeQuery(query);
             DefaultTableModel tm = (DefaultTableModel) TableBarang.getModel();
             tm.setRowCount(0);
             
             while(rs.next()){
//                 System.out.println("id siswa: "+rs.getString(1)+"\n"+"nama siswa: "+rs.getString(2)+"\n");
                 Object barang[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                 tm.addRow(barang);
             }
            
        }catch (Exception e) {
            System.out.println("error : "+ e.getMessage());
        } 
    }//GEN-LAST:event_ShowBarangActionPerformed
    
    
    //tombol dan fungsi untuk membersihkan field
    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
        // TODO add your handling code here:
        NamaBarang.setText("");
        MerekBarang.setText("");
        GrupJenis.clearSelection(); 
        PanjangBarang.setText("");
        LebarBarang.setText("");
        TanggalMasuk.setText("");
        TujuanBarang.setText("");
        TanggalKeluar.setText("");
    }//GEN-LAST:event_BersihActionPerformed
    
    
    
    //tombol dan fungsi untuk edit data
    private void TombolUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolUpActionPerformed
        // TODO add your handling code here:
        String noshow = NoBarang.getText();
        
        
        namaup = NamaBarang.getText();
        merekup = MerekBarang.getText();
        jenisup = "";
            if (PecahBelah.isSelected()){
                 jenisup = PecahBelah.getText();
                }
            else if (Normal.isSelected()){
                 jenisup = Normal.getText();
                }
            else{
                 jenisup = "belum memilih";
                }
        panjangup = PanjangBarang.getText();
        lebarup = LebarBarang.getText();
        tanggalmasukup = TanggalMasuk.getText();
        tujuanup = TujuanBarang.getText();
        tanggalkeluarup = TanggalKeluar.getText();
        noup = NoBarang.getText();
        
        
        
        try{
            
            //mengecek ketersediaan id
            String sqlup="select * from daftar_barang where id_barang='"+noshow+"'";

            st=conn.createStatement();
            rs=st.executeQuery(sqlup);
            //end
        
        

                if (NoBarang.getText().equals("")){
                JOptionPane.showMessageDialog(null,"id belum dimasukan", "information", JOptionPane.INFORMATION_MESSAGE );
                }

                else if(rs.next()){

                sql = "UPDATE daftar_barang SET nama_barang='"+namaup+"',merek_barang='"+merekup+"',jenis_barang='"+jenisup+"',panjang_barang='"+panjangup+"'"
                        + ",lebar_barang='"+lebarup+"',tanggal_masuk='"+tanggalmasukup+"',tujuan_barang='"+tujuanup+"',tanggal_keluar='"+tanggalkeluarup+"' WHERE id_barang="+noup;
                ps = conn.prepareStatement(sql);
                
                
                    if (NamaBarang.getText().equals("")) {
                         JOptionPane.showMessageDialog(null, "nama tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    } else if (MerekBarang.getText().equals("")) {
                         JOptionPane.showMessageDialog(null, "merek tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    } else if (PecahBelah.isSelected() == false && Normal.isSelected() == false ) {
                         JOptionPane.showMessageDialog(null, "jenis tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    }else if (PanjangBarang.getText().equals("")) {
                         JOptionPane.showMessageDialog(null, "panjang tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    }else if (LebarBarang.getText().equals("")) {
                         JOptionPane.showMessageDialog(null, "lebar tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    }else if (TanggalMasuk.getText().equals("")) {
                         JOptionPane.showMessageDialog(null, "tanggal masuk tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    }else if (TujuanBarang.getText().equals("")) {
                         JOptionPane.showMessageDialog(null, "tujuan tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    }else if (TanggalKeluar.getText().equals("")) {
                         JOptionPane.showMessageDialog(null, "tanggal keluar tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    }else{
                        int rt = ps.executeUpdate(sql);
                     JOptionPane.showMessageDialog(null,"Data berhasil diupdate", "information", JOptionPane.INFORMATION_MESSAGE );
                    }


                }
                else{
                JOptionPane.showMessageDialog(null,"id tidak ditemukan", "information", JOptionPane.INFORMATION_MESSAGE );
                }
            
        }catch (Exception e) {
            System.out.println("error : "+ e.getMessage());
        } 
        
    }//GEN-LAST:event_TombolUpActionPerformed

    
    //tombol dan fungsi untuk delete data
    private void TombolDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDelActionPerformed
        // TODO add your handling code here:
        String noshow = NoBarang.getText();
        
        
        
          try{

                //mengecek ketersediaan id
               String sqldel="select * from daftar_barang where id_barang='"+noshow+"'";

               st=conn.createStatement();
               rs=st.executeQuery(sqldel);
               //end



                   if (NoBarang.getText().equals("")){
                   JOptionPane.showMessageDialog(null,"id belum dimasukan", "information", JOptionPane.INFORMATION_MESSAGE );
                   }

                   else if(rs.next()){
                        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete data ini ?", "Confirmation",JOptionPane.YES_NO_OPTION);
                        if (ok==JOptionPane.YES_OPTION)
                        {
          
                            String nodel = NoBarang.getText();
                            sql = "DELETE FROM daftar_barang WHERE id_barang ="+nodel;
                            ps = conn.prepareStatement(sql);
                            int rt = ps.executeUpdate(sql);
                            JOptionPane.showMessageDialog(null,"Data berhasil dihapus", "information", JOptionPane.INFORMATION_MESSAGE );
                        }

                   }
                   else{
                       JOptionPane.showMessageDialog(null,"id tidak ditemukan", "information", JOptionPane.INFORMATION_MESSAGE );
                   }

           }catch (Exception e) {
               System.out.println("error : "+ e.getMessage());
           } 
        
        
    }//GEN-LAST:event_TombolDelActionPerformed

   
    
    //tombol dan fungsi untuk menampilkan data ke field
    private void LihatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatDataActionPerformed
        // TODO add your handling code here:
        
        String noshow = NoBarang.getText();
        try
            {
                //mengecek ketersediaan id
                sql="select * from daftar_barang where id_barang='"+noshow+"'";
                
                st=conn.createStatement();
                rs=st.executeQuery(sql);
                //end
                
                
            
                    if (NoBarang.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"id belum dimasukan", "information", JOptionPane.INFORMATION_MESSAGE );
                    }
                    else if(rs.next()){

                        NamaBarang.setText(rs.getString("nama_barang"));
                        MerekBarang.setText(rs.getString("merek_barang"));
                        if(rs.getString("jenis_barang").equals("Pecah belah")){
                            PecahBelah.setSelected(true);
                        }else{
                            Normal.setSelected(true);
                        }

                        PanjangBarang.setText(rs.getString("panjang_barang"));
                        LebarBarang.setText(rs.getString("lebar_barang"));
                        TanggalMasuk.setText(rs.getString("tanggal_masuk"));
                        TujuanBarang.setText(rs.getString("tujuan_barang"));
                        TanggalKeluar.setText(rs.getString("tanggal_keluar"));



                    }
                    else{
                        JOptionPane.showMessageDialog(null,"id tidak ditemukan", "information", JOptionPane.INFORMATION_MESSAGE );
                    }
            }catch(Exception e)
            {
                System.out.println("error : "+ e.getMessage());
            }   
    }//GEN-LAST:event_LihatDataActionPerformed

    private void LebarBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebarBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LebarBarangActionPerformed

    private void ResetBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBarangActionPerformed
        // TODO add your handling code here:
        try{
            int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin merestart no barang ?", "Confirmation",JOptionPane.YES_NO_OPTION);
                if (ok==JOptionPane.YES_OPTION)
                {
                    String sqlreset="ALTER TABLE daftar_barang DROP id_barang;";
                    String sqladd="ALTER TABLE `daftar_barang` ADD `id_barang` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id_barang`);";

                    ps = conn.prepareStatement(sqlreset);
                    int rt = ps.executeUpdate(sqlreset); 

                    ps = conn.prepareStatement(sqladd);
                    int rk = ps.executeUpdate(sqladd); 
                }
        
        }catch(Exception e)
        {
            System.out.println("error : "+ e.getMessage());
        }   
        
    }//GEN-LAST:event_ResetBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bersih;
    private javax.swing.ButtonGroup GrupJenis;
    private javax.swing.JTextField LebarBarang;
    private javax.swing.JButton LihatData;
    private javax.swing.JTextField MerekBarang;
    private javax.swing.JTextField NamaBarang;
    private javax.swing.JTextField NoBarang;
    private javax.swing.JRadioButton Normal;
    private javax.swing.JTextField PanjangBarang;
    private javax.swing.JRadioButton PecahBelah;
    private javax.swing.JButton ResetBarang;
    private javax.swing.JButton ShowBarang;
    private javax.swing.JTable TableBarang;
    private javax.swing.JTextField TanggalKeluar;
    private javax.swing.JTextField TanggalMasuk;
    private javax.swing.JButton TombolDel;
    private javax.swing.JButton TombolUp;
    private javax.swing.JTextField TujuanBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
